# Generated by Django 4.1.2 on 2022-10-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_img', models.ImageField(upload_to='services', verbose_name='Картинка')),
                ('services_title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('services_descriptions', models.CharField(max_length=150, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
    ]
