# Generated by Django 4.1.2 on 2022-10-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitsDescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefits_main_title', models.CharField(max_length=255, verbose_name='Заголовк')),
                ('benefits_description_title', models.CharField(max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Описание преимуществ',
                'verbose_name_plural': 'Описание преимуществ',
            },
        ),
        migrations.CreateModel(
            name='CardsBenefitsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards_img', models.ImageField(upload_to='cards/', verbose_name='Изображение карточки')),
                ('cards_title', models.CharField(max_length=120, verbose_name='Заголовок карточки')),
                ('cards_descriptions', models.CharField(max_length=255, verbose_name='Описание карточки')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
        migrations.AlterField(
            model_name='slidermodel',
            name='slider_img',
            field=models.ImageField(upload_to='sliderimg/', verbose_name='Изображение'),
        ),
    ]
