# Generated by Django 4.1.2 on 2022-10-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_benefitsdescriptionmodel_cardsbenefitsmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_img', models.ImageField(upload_to='latest/', verbose_name='Изображение работ')),
                ('latest_title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('latest_description', models.CharField(max_length=255, verbose_name='Описание работ')),
            ],
            options={
                'verbose_name': 'Последняя работа',
                'verbose_name_plural': 'Послежние работы',
            },
        ),
        migrations.DeleteModel(
            name='BenefitsDescriptionModel',
        ),
    ]
