# Generated by Django 4.1.2 on 2022-10-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_latestwork_delete_benefitsdescriptionmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latestwork',
            options={'verbose_name': 'Последняя работа', 'verbose_name_plural': 'Последние работы'},
        ),
    ]
