# Generated by Django 4.1.2 on 2022-10-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_img', models.ImageField(upload_to='about/', verbose_name='Изображение')),
                ('about_title', models.CharField(max_length=120, verbose_name='Зашоловок')),
                ('about_descriptions', models.CharField(max_length=150, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
